### ISSUE TITLE
"Fatal error in v8::ToLocalChecked" with JS proxy objects and attached Ruby proc

### ISSUE THREAD

**Issue by JasonBarnabe** [rubyjs/mini_racer#155]
Trying to write a script that records JS function calls, but it's crashing in some scenarios. Minimized test case:

```ruby
require 'mini_racer'
js = <<~JS
  function MyProxy(reference) {
    return new Proxy(function() {}, {
      get: function(obj, prop) {
        return new MyProxy(reference.concat(prop));
      },
      apply: function(target, thisArg, argumentsList) {
        myFunctionLogger(reference);
      }
    });
  };
  (new MyProxy([])).function_call(new MyProxy([])-1)
JS
context = MiniRacer::Context.new(timeout: 500, max_memory: 20_000_000)
context.attach('myFunctionLogger', ->(property) { })
context.eval(js)
```

```
#
# Fatal error in v8::ToLocalChecked
# Empty MaybeLocal.
#

/home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:201: [BUG] Illegal instruction at 0x00007fbbfa567ed2
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]

-- Control frame information -----------------------------------------------
c:0027 p:---- s:0136 e:000135 CFUNC  :eval_unsafe
c:0026 p:0011 s:0130 e:000129 BLOCK  /home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:201
c:0025 p:0107 s:0127 E:0011d8 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:307
c:0024 p:0010 s:0116 E:000540 BLOCK  /home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:200 [FINISH]
c:0023 p:---- s:0113 e:000112 CFUNC  :synchronize
c:0022 p:0061 s:0109 E:002428 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:198
c:0021 p:0008 s:0102 e:000101 EVAL   (irb):17 [FINISH]
c:0020 p:---- s:0099 e:000098 CFUNC  :eval
c:0019 p:0021 s:0091 e:000090 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/workspace.rb:85
c:0018 p:0056 s:0083 e:000081 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/context.rb:385
c:0017 p:0020 s:0074 e:000073 BLOCK  /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:493
c:0016 p:0025 s:0071 e:000070 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:647
c:0015 p:0008 s:0065 e:000064 BLOCK  /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:490
c:0014 p:0100 s:0060 e:000059 BLOCK  /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/ruby-lex.rb:246 [FINISH]
c:0013 p:---- s:0056 e:000055 CFUNC  :loop
c:0012 p:0006 s:0052 e:000051 BLOCK  /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/ruby-lex.rb:232 [FINISH]
c:0011 p:---- s:0049 e:000048 CFUNC  :catch
c:0010 p:0012 s:0044 e:000043 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/ruby-lex.rb:231
c:0009 p:0034 s:0040 E:001508 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:489
c:0008 p:0005 s:0035 e:000034 BLOCK  /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:428 [FINISH]
c:0007 p:---- s:0032 e:000031 CFUNC  :catch
c:0006 p:0064 s:0027 E:0014f8 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:427
c:0005 p:0102 s:0022 e:000021 METHOD /home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:383
c:0004 p:0019 s:0016 e:000015 TOP    /home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11 [FINISH]
c:0003 p:---- s:0013 e:000012 CFUNC  :load
c:0002 p:0109 s:0008 E:000930 EVAL   /home/jason/.rbenv/versions/2.6.2/bin/irb:23 [FINISH]
c:0001 p:0000 s:0003 E:001f90 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
/home/jason/.rbenv/versions/2.6.2/bin/irb:23:in `<main>'
/home/jason/.rbenv/versions/2.6.2/bin/irb:23:in `load'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:383:in `start'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:427:in `run'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:427:in `catch'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:428:in `block in run'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:489:in `eval_input'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `each_top_level_statement'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/ruby-lex.rb:231:in `catch'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/ruby-lex.rb:232:in `loop'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:490:in `block in eval_input'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:647:in `signal_status'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb.rb:493:in `block (2 levels) in eval_input'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/context.rb:385:in `evaluate'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/workspace.rb:85:in `evaluate'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/2.6.0/irb/workspace.rb:85:in `eval'
(irb):17:in `irb_binding'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:198:in `eval'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:198:in `synchronize'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:200:in `block in eval'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:307:in `timeout'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:201:in `block (2 levels) in eval'
/home/jason/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/mini_racer-0.2.8/lib/mini_racer.rb:201:in `eval_unsafe'

-- Machine register context ------------------------------------------------
 RIP: 0x00007fbbfa567ed2 RBP: 0x00007ffd2aa10a30 RSP: 0x00007ffd2aa10a18
 RAX: 0x000000000000003e RBX: 0x00005647a3d63240 RCX: 0x0000000000000000
 RDX: 0x00007fbbfdaf7b80 RDI: 0x00007ffd2aa0e260 RSI: 0x0000000000000000
  R8: 0x000000000000003e  R9: 0x000000000000003e R10: 0x00007fbbf9cd4a4a
 R11: 0x00007fbbfa567ec0 R12: 0x00005647a3d63240 R13: 0x0000000000000000
 R14: 0x00005647a3db8270 R15: 0x00007ffd2aa10a60 EFL: 0x0000000000010202

-- C level backtrace information -------------------------------------------
SEGV received in ILL handler
Aborted (core dumped)
```

**Comment by SamSaffron** [comment]
Thanks for reporting, I have this fixed in 0.2.9
