### ISSUE TITLE
Problem when installing on ARM debian buster

### ISSUE THREAD

**Issue by ShareOut** [rubyjs/mini_racer#182]
Hi,

I am trying to install mini_racer for a huginn installation on a debian buster arm PI. I have no experience with ruby nor libv8.
Due to an error, I had to install the libv8 gem with --with-system-v8.
I tried to install v8 on the system (apt-get install libv8-dev) and since I am on debian buster, the package is replaced by libnode-dev from this version of debian.

Now I can't install mini_racer because libv8 is not foud on my system :
`
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: /home/huginn/huginn/vendor/bundle/ruby/2.6.0/gems/mini_racer-0.2.4/ext/mini_racer_extension
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.6.0 -r ./siteconf20201124-17048-ef84u5.rb extconf.rb --with-system-v8
checking for -lpthread... yes
**checking for v8.h... no**
*** extconf.rb failed ***

`

I don't know how to use --with-v8-dir and how to find the right folder.

Can someone help me please, thank you.

**Comment by adlugopolski** [comment]
This is not an issue with the gem itself. I think places like StackOverflow might a better venue to look for help in solving this kind of configuration issues. 🙂

**Comment by SamSaffron** [comment]
can you install the libv8 gem with `gem install libv8` 

That is the first thing to sort out here.

**Comment by ShareOut** [comment]
I understand this is not the type of questions for github. So many thanks if you can help me.

In my bundle I need mini_racer 0.2.4 => libv8-6.13.292.48.1 so here is the output of `gem install libv8 -v '6.3.292.48.1' --source 'https://rubygems.org/'`

########
Traceback (most recent call last):
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 2679, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 2665, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 2420, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 1497, in RunOnDeps
    work_queue.flush(revision_overrides, command, args, options=self._options)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient_utils.py", line 931, in flush
    self._run_one_task(self.queued.pop(i), args, kwargs)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient_utils.py", line 1023, in _run_one_task
    task_item.run(*args, **kwargs)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 903, in run
    self.ParseDepsFile()
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient.py", line 698, in ParseDepsFile
    gclient_eval.Exec(deps_content, global_scope, local_scope, filepath)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/gclient_eval.py", line 220, in Exec
    _GCLIENT_SCHEMA.validate(local_scope)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/third_party/schema/schema.py", line 254, in validate
    raise SchemaError([k] + x.autos, [e] + x.errors)
third_party.schema.schema.SchemaError: Key 'deps' error:
Key 'buildtools/linux64' error:
Or(None, <type 'basestring'>, {'url': <type 'basestring'>, Optional('condition'): <type 'basestring'>}) did not validate OrderedDict([('packages', [OrderedDict([('package', 'gn/gn/linux-amd64'), ('version', '{gn_version}')])]), ('dep_type', 'cipd'), ('condition', 'host_os == "linux"')])
Missing keys: 'url'
Running: gclient root
Running: gclient config --spec 'solutions = [
  {
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "managed": False,
    "name": "v8",
    "deps_file": "DEPS",
    "custom_deps": {},
  },
]
'
Running: gclient sync --with_branch_heads
Traceback (most recent call last):
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 301, in <module>
    sys.exit(main())
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 296, in main
    return run(options, spec, root)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 290, in run
    return checkout.init()
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 133, in init
    self.run_gclient(*sync_cmd)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 78, in run_gclient
    return self.run(cmd_prefix + cmd, **kwargs)
  File "/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/vendor/depot_tools/fetch.py", line 68, in run
    return subprocess.check_output(cmd, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '('gclient', 'sync', '--with_branch_heads')' returned non-zero exit status 1
/usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/ext/libv8/builder.rb:117:in `block in setup_build_deps!': unable to fetch v8 source (RuntimeError)
	from /usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/ext/libv8/builder.rb:115:in `chdir'
	from /usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/ext/libv8/builder.rb:115:in `setup_build_deps!'
	from /usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/ext/libv8/builder.rb:71:in `build_libv8!'
	from /usr/local/lib/ruby/gems/2.6.0/gems/libv8-6.3.292.48.1/ext/libv8/location.rb:24:in `install!'
	from extconf.rb:7:in `<main>'

extconf failed, exit code 1
###############

So I managed to install with apt-get and --with-system-v8.
apt-get install libnode-dev (-> replace libv8-dev)
gem install libv8 -v '6.3.292.48.1' --source 'https://rubygems.org/' -- --with-system-v8

When I look for the v8.h file that is not foud : 
find / -name "*v8.h*"
/usr/include/nodejs/deps/v8/include/v8.h
/usr/local/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1/vendor/v8/include/v8.h
/usr/local/lib/ruby/gems/2.6.0/gems/libv8-7.3.492.27.1/vendor/v8/src/init/v8.h

Is it a problem between the versions of libv8 on node library and the libv8 gem ?

**Comment by SamSaffron** [comment]
This is certainly not in the right repo :) can you open this on the libv8 repo? 

I strongly recommend starting with absolute latest libv8 before dealing with the hornets nest of getting historical stuff working.

**Comment by ShareOut** [comment]
I can't use the latest version because v8 doesn't compile on ARM since the v6.7.

That said, if the libv8-dev is now replaced by libnode, the lib should be accessible somewhere in the system with node.
Thank you.
