### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by frostmark** [rubyjs/mini_racer#217]
Hi there!

I tried to install `sq_mini_racer` on the new mac OS Monterey but got the following error:

```bash
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/sq_mini_racer-0.3.1.0.4/ext/mini_racer_extension
/Users/markfrost/.asdf/installs/ruby/2.7.4/bin/ruby -I /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0 -r ./siteconf20211027-72771-ys6kxa.rb extconf.rb
  ERROR: found gems matching libv8-node:'~> 15.5.1.0.beta1', but no binary for x86_64-darwin-21
         try "gem install libv8-node:'~> 15.5.1.0.beta1'" to attempt to build libv8-node from source
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/markfrost/.asdf/installs/ruby/2.7.4/bin/$(RUBY_BASE_NAME)
platform ruby:x86_64-darwin21 rubygems:x86_64-darwin-21 detected:x86_64-darwin-21
looking for libv8-node-*-x86_64-darwin-21 in ["/Users/markfrost/.gem/ruby/2.7.0", "/Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0"]
libv8-node-*-x86_64-darwin-21 not found in ["/Users/markfrost/.gem/ruby/2.7.0", "/Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0"]
looking for libv8-node-*-x86_64-darwin-21 in ["/Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/sq_mini_racer-0.3.1.0.4/ext/mini_racer_extension/vendor"]
libv8-node-*-x86_64-darwin-21 not found in ["/Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/sq_mini_racer-0.3.1.0.4/ext/mini_racer_extension/vendor"]

extconf failed, exit code 1

Gem files will remain installed in /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/sq_mini_racer-0.3.1.0.4 for inspection.
Results logged to /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-21/2.7.0/sq_mini_racer-0.3.1.0.4/gem_make.out

  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/builder.rb:99:in `run'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:48:in `block in build'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/tempfile.rb:291:in `open'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/ext_conf_builder.rb:30:in `build'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/builder.rb:169:in `block in build_extension'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `synchronize'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/builder.rb:165:in `build_extension'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/builder.rb:210:in `block in build_extensions'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `each'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/ext/builder.rb:207:in `build_extensions'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/2.7.0/rubygems/installer.rb:844:in `build_extensions'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/rubygems_gem_installer.rb:71:in `build_extensions'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/rubygems_gem_installer.rb:28:in `install'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/source/rubygems.rb:200:in `install'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/worker.rb:62:in `apply_func'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/worker.rb:57:in `block in process_queue'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/worker.rb:54:in `loop'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/worker.rb:54:in `process_queue'
  /Users/markfrost/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

An error occurred while installing sq_mini_racer (0.3.1.0.4), and Bundler cannot continue.

In Gemfile:
  sqreen was resolved to 1.24.1, which depends on
    sq_mini_racer


```

**Comment by misternu** [comment]
@frostmark were you able to resolve this? I'm running into the same problem

**Comment by iJohnPaul** [comment]
I am also facing this issue. Would love to know if anyone has got it resolved.

**Comment by frostmark** [comment]
Heh, no I haven't resolved that, just thought that this is not the place to be for this issue, because as I understood `sq_mini_racer` is a fork of `mini_racer`, but okay I reopened the issue, maybe someone will help us

**Comment by jzisser9** [comment]
Also facing this issue on macOS Monterey 12.0.1. I saw how there was a hack in this issue to fix the problem in Big Sur: https://github.com/rubyjs/mini_racer/issues/173

I've run the script but I can't seem to get `bundler` to use this gem when I try to `bundle install`. I don't directly reference `mini_racer` in my Gemfile, but I use gems that depend on it.

**Comment by SamSaffron** [comment]
Can you see if the pre release of the gem installs ok?

**Comment by misternu** [comment]
I was able to get the libv8-node gem to install with or without the `--pre` option, but sq_mini_racer doesn't use that gem version yet and it doesn't look like a Monterey corresponding binary has been made yet with either 16 or the 15 beta (in https://rubygems.org/gems/libv8-node/versions there are no darwin-21 binaries). Mark is probably right about this issue being in the wrong place, we might need to bring this to the attention of lloeki at https://github.com/sqreen/ruby-libv8-node

**Comment by toddmetheny** [comment]
I'm also having this issue on Monterey. Can anyone share how they resolved?

**Comment by tisba** [comment]
Can you provide some more info, @toddmetheny? The initial issue is a bit dated and there have been several releases of `mini_racer` and `libv8-node` in the meantime. Please also check out https://github.com/rubyjs/mini_racer#troubleshooting.
