### ISSUE TITLE
Build issue on Ruby 3.1

### ISSUE THREAD

**Issue by itay-grudev** [rubyjs/mini_racer#222]
I just updated to Ruby 3.1 and I get the following errors when I run `bundle install` on my project:

```txt
current directory: /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/mini_racer-0.4.0/ext/mini_racer_extension
/home/user/.rbenv/versions/3.1.0/bin/ruby -I /home/user/.rbenv/versions/3.1.0/lib/ruby/site_ruby/3.1.0 -r ./siteconf20220104-41523-qjineq.rb extconf.rb
checking for -lpthread... yes
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/user/.rbenv/versions/3.1.0/bin/$(RUBY_BASE_NAME)
	--with-pthread-dir
	--without-pthread-dir
	--with-pthread-include
	--without-pthread-include=${pthread-dir}/include
	--with-pthread-lib
	--without-pthread-lib=${pthread-dir}/lib
	--with-pthreadlib
	--without-pthreadlib
	--enable-debug
	--disable-debug
	--enable-asan
	--disable-asan
/home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:99:in `find': Tried to load unspecified class: Libv8::Node::Location::Vendor (Psych::DisallowedClass)
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/class_loader.rb:28:in `load'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:424:in `resolve_class'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:213:in `visit_Psych_Nodes_Mapping'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:318:in `visit_Psych_Nodes_Document'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:30:in `visit'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/visitor.rb:6:in `accept'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych/visitors/to_ruby.rb:35:in `accept'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:335:in `safe_load'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/3.1.0/psych.rb:370:in `load'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/libv8-node-15.14.0.0-x86_64-linux/ext/libv8-node/location.rb:21:in `block in load!'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/libv8-node-15.14.0.0-x86_64-linux/ext/libv8-node/location.rb:20:in `open'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/libv8-node-15.14.0.0-x86_64-linux/ext/libv8-node/location.rb:20:in `load!'
	from /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/libv8-node-15.14.0.0-x86_64-linux/lib/libv8/node.rb:8:in `configure_makefile'
	from extconf.rb:64:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/user/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/extensions/x86_64-linux/3.1.0/mini_racer-0.4.0/mkmf.log

extconf failed, exit code 1
```

**Comment by itay-grudev** [comment]
Duplicate of #219. Closing.
