### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension

### ISSUE THREAD

**Issue by shivamsinghchahar** [rubyjs/mini_racer#263]
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/ext/libv8-node
/Users/shivamchahar/.rbenv/versions/3.0.3/bin/ruby -I /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0
extconf.rb
creating Makefile
==== in /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/ext/libv8-node
==== running /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/libexec/download-node
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0-:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
  5 61.6M    5 3566k    0     0   895k      0  0:01:10  0:00:03
 34 61.6M   34 21.5M    0     0  2383k      0  0:00:26  0:00:04  0:00:22 2389k
 52 61.6M   52 32.1M    0     0  4719k      0  0:00:13  0:00:06  0:00:07 6741k
 80 61.6M   80 49.4M    0     0  5580k      0 0:00:11  0:00:08  0:00:03 8745k
100 61.6M  100 56.0M    0     0  5736k      0  0:00:11  0:00:10  0:00:01 9051k
61.6M    0     0  5816k      0  0:00:10  0:00:10 --:--:-- 8416k
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/libexec/../src/node-v16.10.0.tar.gz:
OK
==== in /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/ext/libv8-node
==== running /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/libexec/extract-node
patching file tools/icu/icutrim.py
patching file tools/genv8constants.py
==== in /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/ext/libv8-node
==== running /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/libexec/build-libv8
parallel job count: 12
configure: --openssl-no-asm --without-npm --shared --with-intl=full-icu
compilers: CC='clang' CXX='clang++' CC_host='' CXX_host=''
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
Please use python3.9 or python3.8 or python3.7 or python3.6.
	/usr/local/bin/python3.9 configure
	/usr/local/bin/python3.8 configure
Node.js configure: Found Python 3.10.6...
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/ext/libv8-node/builder.rb:14:in
`build_libv8!': failed to build libv8 16.10.0 (Libv8::Node::BuilderError)
from /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0/ext/libv8-node/location.rb:30:in
`install!'
	from extconf.rb:9:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/libv8-node-16.10.0.0 for
inspection.
Results logged to
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/extensions/x86_64-darwin-21/3.0.0/libv8-node-16.10.0.0/gem_make.out

  /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:102:in `run'
  /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/ext_conf_builder.rb:28:in `build'
  /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:171:in `build_extension'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:205:in `block in
build_extensions'
  /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:202:in `each'
  /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/ext/builder.rb:202:in `build_extensions'
  /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/site_ruby/3.0.0/rubygems/installer.rb:843:in `build_extensions'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/rubygems_gem_installer.rb:71:in
`build_extensions'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/rubygems_gem_installer.rb:28:in
`install'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/source/rubygems.rb:200:in
`install'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/installer/gem_installer.rb:54:in
`install'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:186:in
`do_install'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:177:in
`block in worker_pool'
  /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/worker.rb:62:in `apply_func'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/worker.rb:57:in `block in
process_queue'
  /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/worker.rb:54:in `loop'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/worker.rb:54:in
`process_queue'
/Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/lib/bundler/worker.rb:91:in `block (2
levels) in create_threads'

An error occurred while installing libv8-node (16.10.0.0), and Bundler cannot continue.

In Gemfile:
  mini_racer was resolved to 0.6.3, which depends on
    libv8-node
```
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.22
  - RUBY VERSION: 3.0.3 (2021-11-24 patchlevel 157) [x86_64-darwin21]
  - INSTALLATION DIRECTORY: /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /Users/shivamchahar/.gem/ruby/3.0.0
  - RUBY EXECUTABLE: /Users/shivamchahar/.rbenv/versions/3.0.3/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/shivamchahar/.rbenv/versions/3.0.3/bin
  - SPEC CACHE DIRECTORY: /Users/shivamchahar/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/shivamchahar/.rbenv/versions/3.0.3/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-21
  - GEM PATHS:
     - /Users/shivamchahar/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0
     - /Users/shivamchahar/.gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/shivamchahar/.rbenv/versions/3.0.3/bin
     - /usr/local/Cellar/rbenv/1.2.0/libexec
     - /usr/local/opt/libpq/bin
     - /Users/shivamchahar/.rbenv/shims
     - /Users/shivamchahar/.nvm/versions/node/v16.14.2/bin
     - /Library/Frameworks/Python.framework/Versions/2.7/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /Library/Apple/usr/bin
     - /Users/shivamchahar/.fig/bin
     - /Users/shivamchahar/.local/bin
     - /Users/shivamchahar/Library/Android/sdk/emulator
     - /Users/shivamchahar/Library/Android/sdk/tools
     - /Users/shivamchahar/Library/Android/sdk/tools/bin
     - /Users/shivamchahar/Library/Android/sdk/platform-tools
```

```
gem list libv8

*** LOCAL GEMS ***

libv8-node (18.8.0.0 x86_64-darwin, 16.10.0.0 x86_64-darwin, 15.14.0.1 x86_64-darwin-21)
```

I'm getting this error after adding `x86_64-linux` platform to `Gemfile.lock`. I can see it's something related to python. I have 3.8, 3.9 and 3.10 installed on my local machine.

**Comment by tisba** [comment]
Please make sure to follow all steps in https://github.com/rubyjs/mini_racer#troubleshooting. Especially your bundler version looks quite old.

This looks also quite a bit like https://github.com/rubyjs/mini_racer/issues/250, so closing this one.
